info:
  title: 喵喵快乐小窝
  subtitle: 🥝
  author: oneko
  url: https://www.oneko.cc

defaults:
  favicon: https://www.zako.im/favicon.ico
  logo: 
  avatar: https://www.zako.im/images/avatar.webp

colors:
  primary: "#FE7BB5"
  secondary:
  default_mode: light

global:
  fonts:
    chinese: 
      enable: false
      family:
      url:
    english: 
      enable: false
      family:
      url:
    title:
      enable: false
      family:
      url:
  content_max_width: 1000px
  sidebar_width: 210px
  hover:
    shadow: true
    scale: false
  scroll_progress:
    bar: false
    percentage: true
  website_counter:
    url: https://cn.vercount.one/js
    enable: true
    site_pv: true
    site_uv: true
    post_pv: true
  single_page: true
  preloader:
    enable: false
    custom_message:
  side_tools:
    gear_rotation: true
    auto_expand: false
  open_graph:
    enable: false
    image: /images/redefine-og.webp
    description: Hexo Theme Redefine, Redefine Your Hexo Journey.
  google_analytics:
    enable: false
    id:

fontawesome:
  thin: false
  light: false
  duotone: false
  sharp_solid: false

home_banner:
  enable: true
  style: fixed
  image: 
    light: /images/bg_light.jpg
    dark: /images/bg_dark.jpg
  title: OvO
  subtitle:
    text: ["This is the first message", "This is the second message", "etc"]
    hitokoto:
      enable: true
      show_author: false
      api: https://v1.hitokoto.cn
    typing_speed: 100
    backing_speed: 80
    starting_delay: 500
    backing_delay: 1500
    loop: true
    smart_backspace: true
  text_color: 
    light: "#fff"
    dark: "#d1d1b6"
  text_style: 
    title_size: 2.8rem
    subtitle_size: 1.5rem
    line_height: 1.2
  custom_font: 
    enable: false
    family:
    url:
  social_links:
    enable: true
    style: default
    links:
      github: https://github.com/xiaorona
      instagram:
      zhihu:
      twitter: https://x.com/xiaorona_
      email: x@example.com
    qrs:
      weixin:

navbar:
  auto_hide: true
  color:
    left: "#f78736"
    right: "#367df7"
    transparency: 35
  width:
    home: 1200px
    pages: 1000px
  links:
    Home: 
      path: /
      icon: fa-solid fa-house
    Archives: 
      path: /archives
      icon: fa-solid fa-box-archive
    Tags: 
      path: /tags/
      icon: fa-solid fa-tags
    Categories: 
      path: /categories/
      icon: fa-solid fa-folder
    Albums: 
      path: /masonry/
      icon: fa-solid fa-image
    Bookmarks: 
      path: /bookmarks/
      icon: fa-solid fa-bookmark
    About: 
      icon: fa-solid fa-circle-info
      submenus:
        Me: /about
    Links: 
      icon: fa-solid fa-square-up-right
      submenus:
        Link1: https://example.com
        Link2: /links/
  search:
    enable: true
    preload: true

home:
  sidebar:
    enable: true
    position: left
    first_item: menu
    announcement:
    show_on_mobile: true
    links:
      Archives: 
        path: /archives
        icon: fa-regular fa-archive
      Tags: 
        path: /tags
        icon: fa-regular fa-tags
      Categories: 
        path: /categories
        icon: fa-regular fa-folder
  article_date_format: auto
  excerpt_length: 200
  categories:
    enable: true
    limit: 3
  tags:
    enable: true
    limit: 3

articles:
  style:
    font_size: 16px
    line_height: 1.5
    image_border_radius: 14px
    image_alignment: center
    image_caption: false
    link_icon: true
    delete_mask: false
    title_alignment: left
    headings_top_spacing:
      h1: 3.2rem
      h2: 2.4rem
      h3: 1.9rem
      h4: 1.6rem
      h5: 1.4rem
      h6: 1.3rem
  word_count:
    enable: true
    count: true
    min2read: true
  author_label: 
    enable: false
    auto: false
    list: []
  code_block:
    copy: true
    style: mac
    highlight_theme:
      light: github
      dark: vs2015
    font:
      enable: false
      family:
      url:
  toc:
    enable: true
    max_depth: 3
    number: false
    expand: true
    init_open: true
  copyright:
    enable: true
    default: cc_by_nc_sa
  lazyload: true
  pangu_js: false
  recommendation:
    enable: false
    title: 推荐阅读
    limit: 3
    mobile_limit: 2
    placeholder: /images/wallhaven-wqery6-light.webp
    skip_dirs: []

comment:
  enable: false
  system: waline
  config:
    waline:
      serverUrl: https://example.example.com
      lang: zh-CN
      emoji: []
      recaptchaV3Key:
      turnstileKey:
      reaction: false
    gitalk:
      clientID:
      clientSecret:
      repo:
      owner:
      proxy:
    twikoo:
      version: 1.6.10
      server_url:
      region:
    giscus:
      repo:
      repo_id:
      category:
      category_id:
      mapping: pathname
      strict: 0
      reactions_enabled: 1
      emit_metadata: 0
      lang: en
      input_position: bottom
      loading: lazy

footer:
  runtime: true
  icon: ''
  start: 2025/03/21 12:00:00
  statistics: true
  customize:
  icp:
    enable: true
    number: 桂ICP备2025068570号
    url:

inject:
  enable: false
  head: 
    -
    -
  footer:
    -
    -

plugins:
  feed:
    enable: false
  aplayer:
    enable: false
    type: fixed
    audios:
      - name:
        artist:
        url:
        cover:
        lrc:
  mermaid:
    enable: false
    version: "11.4.1"

page_templates:
  friends_column: 2
  tags_style: blur

cdn:
  enable: false
  provider: npmmirror
  custom_url:

developer:
  enable: false